// Mixed KV: f16 K + xyzkv2 V

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_F16, GGML_TYPE_XYZKV2_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_F16, GGML_TYPE_XYZKV2_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_F16, GGML_TYPE_XYZKV2_0);
