// GENERATED by tools/gen_gdn_pro.sh -- do not edit. Lines 4373-4561 of the fork's ggml-cuda.cu
// (609423e), verbatim: ggml_cuda_gdn_conv_replay_args, k_gdn_conv_replay, k_gdn_alpha_beta_prologue.
#include "common.cuh"
#include "unary.cuh"

struct ggml_cuda_gdn_conv_replay_args {
    const char *    state;             // conv state table (cell rows)
    const char *    pack;              // pack table (cell rows)
    const int32_t * s_row;             // s_copy[0]: the cell this sequence reads
    size_t          state_row_stride;
    size_t          pack_row_stride;
    const int32_t * conv_idx;          // W rows into [state ++ pack]
    const char *    qkv;               // this batch's inputs [C, n], channel-fastest
    size_t          qkv_nb1;
    float *         state_dst;         // commit: state row at kv_head, [C, W]
    float *         pack_dst;          // park: pack row at kv_head, [C, n]
    size_t          pack_dst_nb1;
    const char *    conv_weight;
    size_t          conv_weight_nb1;
    float *         conv_silu;         // [C, n]
    float *         qk_norm;           // [128, 32, n]
    float           eps;
    float           bias0;             // runtime 0.0f: ssm_conv_f32's absent bias, added as it does
};

template <int n_tokens>
static __global__ void k_gdn_conv_replay(ggml_cuda_gdn_conv_replay_args args) {
    constexpr int channels           = 10240;
    constexpr int channels_per_block = 128;
    constexpr int conv_width         = 4;
    constexpr int old_steps          = conv_width - 1;
    constexpr int qk_blocks          = 32;

    const int tid     = threadIdx.x;
    const int channel = blockIdx.x * channels_per_block + tid;
    const int srow    = args.s_row[0];
    const float * st  = (const float *) (args.state + (size_t) srow * args.state_row_stride);
    const float * pk  = (const float *) (args.pack  + (size_t) srow * args.pack_row_stride);

    float window[old_steps + n_tokens];
#pragma unroll
    for (int w = 0; w < old_steps; ++w) {
        const int r = args.conv_idx[w];
        window[w] = r < old_steps ? st[r * channels + channel] : pk[(r - old_steps) * channels + channel];
    }
#pragma unroll
    for (int j = 0; j < n_tokens; ++j) {
        window[old_steps + j] = *(const float *) (args.qkv + (size_t) j * args.qkv_nb1 + (size_t) channel * sizeof(float));
    }
    // commit and park AFTER every read of this channel (the kv_head cell may be the cell just read)
#pragma unroll
    for (int w = 0; w < old_steps; ++w) {
        args.state_dst[w * channels + channel] = window[w];
    }
#pragma unroll
    for (int j = 0; j < n_tokens; ++j) {
        *(float *) ((char *) args.pack_dst + (size_t) j * args.pack_dst_nb1 + (size_t) channel * sizeof(float)) =
            window[old_steps + j];
    }

    float weight[conv_width];
#pragma unroll
    for (int j = 0; j < conv_width; ++j) {
        weight[j] = *(const float *) (args.conv_weight + (size_t) channel * args.conv_weight_nb1 + j * sizeof(float));
    }

    __shared__ float conv_shared[n_tokens][channels_per_block];
#pragma unroll
    for (int token = 0; token < n_tokens; ++token) {
        float sum = 0.0f;
#pragma unroll
        for (int j = 0; j < conv_width; ++j) {
            sum += window[token + j] * weight[j];
        }
        sum += args.bias0;
        const float value = ggml_cuda_op_silu_single(sum);
        args.conv_silu[token * channels + channel] = value;
        conv_shared[token][tid] = value;
    }
    __syncthreads();

    if (blockIdx.x < qk_blocks && tid < WARP_SIZE) {
#pragma unroll
        for (int token = 0; token < n_tokens; ++token) {
            float sum = 0.0f;
#pragma unroll
            for (int col = tid; col < channels_per_block; col += WARP_SIZE) {
                const float value = conv_shared[token][col];
                sum += value * value;
            }
            sum = warp_reduce_sum<WARP_SIZE>(sum);
            const float scale = rsqrtf(fmaxf(sum, args.eps * args.eps));
#pragma unroll
            for (int col = tid; col < channels_per_block; col += WARP_SIZE) {
                args.qk_norm[(token * qk_blocks + blockIdx.x) * channels_per_block + col] =
                    scale * conv_shared[token][col];
            }
        }
    }
}

static __global__ void k_gdn_alpha_beta_prologue(
        const nv_bfloat16 * alpha_weight, const nv_bfloat16 * beta_weight, const float * activations,
        const float * dt, const float * a, float * gate, float * beta) {
    constexpr int n_embd = 5120;
    constexpr int rank = 48;
    constexpr int n_tokens = 5;
    constexpr int block_size = 256;
    constexpr int ncols2 = n_embd / 2;

    const int row = blockIdx.x;
    const int tid = threadIdx.x;
    const nv_bfloat162 * alpha2 = (const nv_bfloat162 *) (alpha_weight + row * n_embd);
    const nv_bfloat162 * beta2  = (const nv_bfloat162 *) (beta_weight  + row * n_embd);
    const float2 * activations2 = (const float2 *) activations;
    float alpha_sum[n_tokens] = { 0.0f };
    float beta_sum[n_tokens]  = { 0.0f };

    for (int col2 = tid; col2 < ncols2; col2 += block_size) {
        const nv_bfloat162 alpha_value = alpha2[col2];
        const nv_bfloat162 beta_value  = beta2[col2];
#pragma unroll
        for (int token = 0; token < n_tokens; ++token) {
            const float2 x = activations2[token * ncols2 + col2];
            ggml_cuda_mad(alpha_sum[token], alpha_value.x, x.x);
            ggml_cuda_mad(alpha_sum[token], alpha_value.y, x.y);
            ggml_cuda_mad(beta_sum[token], beta_value.x, x.x);
            ggml_cuda_mad(beta_sum[token], beta_value.y, x.y);
        }
    }

    __shared__ float alpha_warp[WARP_SIZE];
    __shared__ float beta_warp[WARP_SIZE];
    if (tid < WARP_SIZE) {
        alpha_warp[tid] = 0.0f;
        beta_warp[tid] = 0.0f;
    }
    __syncthreads();

#pragma unroll
    for (int token = 0; token < n_tokens; ++token) {
        alpha_sum[token] = warp_reduce_sum<WARP_SIZE>(alpha_sum[token]);
        beta_sum[token] = warp_reduce_sum<WARP_SIZE>(beta_sum[token]);
        alpha_warp[tid / WARP_SIZE] = alpha_sum[token];
        beta_warp[tid / WARP_SIZE] = beta_sum[token];
        __syncthreads();
        if (tid < WARP_SIZE) {
            alpha_sum[token] = warp_reduce_sum<WARP_SIZE>(alpha_warp[tid]);
            beta_sum[token] = warp_reduce_sum<WARP_SIZE>(beta_warp[tid]);
        }
        __syncthreads();
    }

    if (tid < n_tokens) {
        const float biased = alpha_sum[tid] + dt[row];
        const float softplus = biased > 20.0f ? biased : logf(1.0f + expf(biased));
        gate[tid * rank + row] = softplus * a[row];
        beta[tid * rank + row] = 1.0f / (1.0f + expf(-beta_sum[tid]));
    }
}

#include "kernels.h"

namespace eng {

void gdn_alpha_beta(cudaStream_t st, const void * alpha_w, const void * beta_w, const float * x, const float * dt,
                    const float * a, float * gate, float * beta) {
    // ggml_cuda_try_fuse_gdn_alpha_beta_prologue's launch
    k_gdn_alpha_beta_prologue<<<48, 256, 0, st>>>((const nv_bfloat16 *) alpha_w, (const nv_bfloat16 *) beta_w, x, dt, a,
        gate, beta);
}

void gdn_conv_replay(cudaStream_t st, const ConvReplay & c, int n_tokens) {
    ggml_cuda_gdn_conv_replay_args args = {};
    args.state            = c.state;
    args.pack             = c.pack;
    args.s_row            = c.s_row;
    args.state_row_stride = c.state_row_stride;
    args.pack_row_stride  = c.pack_row_stride;
    args.conv_idx         = c.conv_idx;
    args.qkv              = (const char *) c.qkv;
    args.qkv_nb1          = c.qkv_nb1;
    args.state_dst        = c.state_dst;
    args.pack_dst         = c.pack_dst;
    args.pack_dst_nb1     = c.pack_dst_nb1;
    args.conv_weight      = (const char *) c.conv_weight;
    args.conv_weight_nb1  = c.conv_weight_nb1;
    args.conv_silu        = c.conv_silu;
    args.qk_norm          = c.qk_norm;
    args.eps              = c.eps;
    args.bias0            = 0.0f;
    const int grid = 10240 / 128;
    switch (n_tokens) {
        case 5: k_gdn_conv_replay<5><<<grid, 128, 0, st>>>(args); break;
        case 1: k_gdn_conv_replay<1><<<grid, 128, 0, st>>>(args); break;
        case 2: k_gdn_conv_replay<2><<<grid, 128, 0, st>>>(args); break;   // the budget end: G + 1 columns
        case 3: k_gdn_conv_replay<3><<<grid, 128, 0, st>>>(args); break;
        case 4: k_gdn_conv_replay<4><<<grid, 128, 0, st>>>(args); break;
        default: fprintf(stderr, "gdn_conv_replay: %d tokens not instantiated\n", n_tokens); abort();
    }
}

} // namespace eng
